services:
  app:
    image: hello-front
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/todo-frontend
      - frontend-build:/usr/src/todo-frontend/build
    container_name: todo-front
  todo-backend:
    image: todo-backend-prod
    depends_on:
      - redis
      - mongo
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    volumes:
      - ./todo-backend:/usr/src/todo-backend 
    container_name: todo-backend

volumes:
  frontend-build: